name: Release NPM package

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release new version
    runs-on: [self-hosted, clancy]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.10'
          registry-url: 'https://registry.npmjs.org'
          scope: '@maptiler'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Prepare package version
        run: |
         ./scripts/getLatestVersionFromTags.cjs packages/core
         cat packages/core/package.json | grep version

      - name: Publish package to NPM
        run: yarn workspace @maptiler/upload-js npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Disable Corepack
        run: corepack disable
