name: Release NPM package

permissions:
  id-token: write  # Required for NPM trusted publishing
  contents: read

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Prepare package version
        run: |
          ./scripts/setPackageVersion.cjs packages/core
          cat packages/core/package.json | grep version

      - name: Publish package to NPM
        run: |
          cd packages/core
          npm publish --access public

      - name: Disable Corepack
        run: corepack disable
